/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:9734eaeb-0716-45d8-83d2-574a32b1e3f4",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_kg8lZvv23",
    "aws_user_pools_web_client_id": "66u7hk15jktqqv63oeq18h5h2l",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://g6ap46qlnfco3a34l7o2an77ny.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-jpd2at3axvcu5autiejyw6pssy",
    "aws_user_files_s3_bucket": "mtbucket104149-dev",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
